spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url:jdbc:mysql://localhost:3306/todo}
    username: ${db.username:root}
    password: ${db.password:1234}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH2_CLIENT_ID:d3c1eecfb60e70ad8f07}
            client-secret: ${OAUTH2_CLIENT_SECRET:a4856ee92b083e88ba51534a5bcec7141ff9bf1b}
            scope: user, user:email
            redirect-uri: ${OAUTH2_REDIRECT_URI:http://43.203.35.49:8000/login/oauth2/code/github}
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

server:
  port: 8000

oauth2:
  frontUri: ${FRONT_URI:https://vuetodo.site/token}

jwt:
  secretKey: ${JWT_SECRET_KEY:prodprodprodprodprodprodprodprodprodprodprodprodprodprodprodprodprodprodprodprod}
  accessTokenExpireTime: 6000000
  refreshTokenExpireTime: 6000000
